version: "3"

services:
  rabbitmq:
    image: rabbitmq:3.7-management
    container_name: rabbitmq
    expose:
      - 5672
      - 15672
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - demo-spring-cloud-stream
  producer:
    build: ../producer
    image: ${PRODUCER_IMAGE_NAME}
    expose:
      - 8080
    ports:
      - 8080:8080
    environment:
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_PORT: ${RABBITMQ_PORT}
      RABBITMQ_USER: ${RABBITMQ_USER}
      RABBITMQ_PASS: ${RABBITMQ_PASS}
    depends_on:
      - rabbitmq
    networks:
      - demo-spring-cloud-stream
  consumer1: &consumer-instance
    build: ../consumer
    image: ${CONSUMER_IMAGE_NAME}
    environment:
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_PORT: ${RABBITMQ_PORT}
      RABBITMQ_USER: ${RABBITMQ_USER}
      RABBITMQ_PASS: ${RABBITMQ_PASS}
    depends_on:
      - rabbitmq
    networks:
      - demo-spring-cloud-stream
  consumer2:
    <<: *consumer-instance
  consumer3:
    <<: *consumer-instance
  consumer4:
    <<: *consumer-instance
  consumer5:
    <<: *consumer-instance

networks:
  demo-spring-cloud-stream:
